'use client';

export default function ContractBanner() {
  return (
    <div className="glass-card border-amber-500/30 bg-amber-500/5 p-6 text-center">
      <div className="text-3xl mb-3">🔧</div>
      <h3 className="font-display text-lg font-bold text-amber-300 mb-2">
        Contract Not Configured
      </h3>
      <p className="font-body text-sm text-slate-400 max-w-md mx-auto leading-relaxed">
        Deploy the Soroban contract to Stellar testnet, then set{' '}
        <code className="font-mono text-amber-400 bg-amber-500/10 px-1.5 py-0.5 rounded text-xs">
          NEXT_PUBLIC_CONTRACT_ID
        </code>{' '}
        in your <code className="font-mono text-slate-300 text-xs">.env.local</code> file.
      </p>
      <div className="mt-4 p-3 rounded-lg bg-slate-800/60 text-left font-mono text-xs text-slate-400 border border-slate-700/40">
        <p className="text-slate-500"># contract/.deployment.env (generated by deploy.sh)</p>
        <p className="text-cyan-400 mt-1">NEXT_PUBLIC_CONTRACT_ID=C...</p>
      </div>
      <a
        href="https://developers.stellar.org/docs/smart-contracts/getting-started/setup"
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-1.5 mt-4 text-sm text-amber-400 hover:text-amber-300 transition-colors font-body"
      >
        Setup Guide
        <svg width="12" height="12" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
          <path strokeLinecap="round" strokeLinejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
        </svg>
      </a>
    </div>
  );
}
